module.exports = 
    ENG: "English"
    RUS: "Russian"
    SPA: "Spanish (Spain)"
    PLS: "Polish"
    TRK: "Turkish"
    GEO: "Georgian"
    CHI: "Chinese (Traditional) ITA: Italian"
    SWE: "Swedish"
    BEL: "Belarusian"
    FRE: "French"
    UKR: "Ukrainian"
    ARA: "Arabic"